Repository orobix/quadra, pull requests merged in 2023-07, with the labels that each got.

#25 Hotfix/wrong segmentation dataloader
  CHANGELOG.md
  README.md
  pyproject.toml
  quadra/__init__.py
  quadra/datamodules/segmentation.py
Labels: bug

#27 Hotfix/wrong extension handling anomaly
  CHANGELOG.md
  pyproject.toml
  quadra/__init__.py
  quadra/datamodules/base.py
  quadra/datasets/anomaly.py
Labels: bug

#28 fix: Fix circular import making code not running properly
  quadra/datamodules/base.py
  quadra/datamodules/classification.py
  quadra/datasets/anomaly.py
  quadra/utils/utils.py
Labels: bug

#22 Refactor/evaluation task
  docs/tutorials/examples/sklearn_classification.md
  docs/tutorials/examples/sklearn_patch_classification.md
  quadra/configs/experiment/base/classification/sklearn_classification_patch_test.yaml
  quadra/configs/experiment/base/classification/sklearn_classification_test.yaml
  quadra/configs/experiment/base/segmentation/smp_evaluation.yaml
  quadra/configs/experiment/base/segmentation/smp_multiclass.yaml
  quadra/configs/experiment/base/segmentation/smp_multiclass_evaluation.yaml
  quadra/configs/task/segmentation_evaluation.yaml
  quadra/configs/task/sklearn_classification_patch_test.yaml
  quadra/configs/task/sklearn_classification_test.yaml
  quadra/tasks/anomaly.py
  quadra/tasks/base.py
  quadra/tasks/classification.py
  quadra/tasks/patch.py
  quadra/tasks/segmentation.py
  tests/tasks/test_classification.py
  tests/tasks/test_segmentation.py
Labels: enhancement

#16 Feature/export generic input shape
  .pre-commit-config.yaml
  docs/tutorials/configurations.md
  docs/tutorials/devices_setup.md
  docs/tutorials/examples/classification.md
  docs/tutorials/examples/multilabel_classification.md
  docs/tutorials/examples/segmentation.md
  docs/tutorials/examples/sklearn_classification.md
  docs/tutorials/examples/sklearn_patch_classification.md
  docs/tutorials/examples/ssl.md
  quadra/configs/experiment/base/classification/classification.yaml
  quadra/configs/experiment/base/classification/sklearn_classification.yaml
  quadra/configs/task/anomalib/cfa.yaml
  quadra/configs/task/anomalib/cflow.yaml
  quadra/configs/task/anomalib/csflow.yaml
  quadra/configs/task/anomalib/draem.yaml
  quadra/configs/task/anomalib/fastflow.yaml
  quadra/configs/task/anomalib/padim.yaml
  quadra/configs/task/anomalib/patchcore.yaml
  quadra/configs/task/classification.yaml
  quadra/configs/task/segmentation.yaml
  quadra/configs/task/sklearn_classification.yaml
  quadra/configs/task/sklearn_classification_patch.yaml
  quadra/configs/task/ssl.yaml
  quadra/datamodules/classification.py
  quadra/datamodules/generic/oxford_pet.py
  quadra/datamodules/segmentation.py
  quadra/models/base.py
  quadra/modules/base.py
  quadra/tasks/anomaly.py
  quadra/tasks/base.py
  quadra/tasks/classification.py
  quadra/tasks/patch.py
  quadra/tasks/segmentation.py
  quadra/tasks/ssl.py
  quadra/utils/export.py
  quadra/utils/mlflow.py
  quadra/utils/tests/models.py
  quadra/utils/utils.py
  tests/models/test_signature_wrapper.py
  tests/tasks/test_anomaly.py
  tests/utilities/test_mlflow_export.py
Labels: enhancement

#30 Fix/network builder kwargs
  quadra/models/classification/backbones.py
Labels: documentation

#32 fix: update readme links to always latest
  README.md
Labels: bug, documentation

#33 fix: update image links with correct relative path
  docs/tutorials/model_management.md
Labels: bug, documentation

#37 Feature/save raw outputs
  CHANGELOG.md
  docs/tutorials/examples/anomaly_detection.md
  quadra/callbacks/anomalib.py
  quadra/configs/callbacks/default_anomalib.yaml
Labels: enhancement
